# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  # Application secret_key_base (run 'rake secret' to generate a new secret)
  secret_key_base: '___secret_that_must_be_replaced_after_deploy___'

  # Application name
  app_name: 'MyApp'

  ### config_ApacheServer_with_uri
  #
  site_domain: 'https://in.xfel.eu/'
  app_sub_domain_uri: 'dev_my_app'
  routes_base_uri: ''
  app_full_url: 'https://in.xfel.eu/dev_my_app'

test:
  secret_key_base: '___secret_that_must_be_replaced_after_deploy___'
  #
  app_name: 'MyApp'
  #
  site_domain: 'https://in.xfel.eu/'
  app_sub_domain_name: 'test_my_app'
  routes_base_uri: ''
  app_full_url: 'https://in.xfel.eu/test_my_app'

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: '___secret_that_must_be_replaced_after_deploy___'
  #
  app_name: 'MyApp'
  #
  site_domain: 'https://in.xfel.eu/'
  app_sub_domain_name: 'my_app'
  routes_base_uri: ''
  app_full_url: 'https://in.xfel.eu/my_app'
